// Enhanced seed script for 25 diverse car products
// Add this to your server.js or create a separate seeder file

const enhancedSampleCars = [
  // Luxury Sedans
  {
    make: "Mercedes",
    model: "S-Class",
    year: 2024,
    price: 450000,
    mileage: 8000,
    fuel: "Petrol",
    transmission: "Automatic",
    bodyType: "Sedan",
    color: "Obsidian Black",
    description: "Ultimate luxury sedan with cutting-edge technology and unparalleled comfort",
    features: ["Massage Seats", "Burmester Sound", "Night Vision", "Executive Rear Seating", "Air Suspension"],
    images: ["mercedes-s-class-2024.jpg"],
    condition: "Used",
    location: "Dubai",
    featured: true,
    verified: true,
  },
  {
    make: "BMW",
    model: "7 Series",
    year: 2023,
    price: 385000,
    mileage: 12000,
    fuel: "Hybrid",
    transmission: "Automatic",
    bodyType: "Sedan",
    color: "Alpine White",
    description: "Executive luxury sedan with hybrid efficiency and advanced driver assistance",
    features: ["Gesture Control", "Laser Headlights", "Sky Lounge", "Bowers & Wilkins Audio"],
    images: ["bmw-7-series-2023.jpg"],
    condition: "Used",
    location: "Abu Dhabi",
    featured: true,
    verified: true,
  },
  {
    make: "Audi",
    model: "A8",
    year: 2024,
    price: 420000,
    mileage: 6000,
    fuel: "Hybrid",
    transmission: "Automatic",
    bodyType: "Sedan",
    color: "Glacier White",
    description: "Tech-forward luxury sedan with quattro all-wheel drive",
    features: ["Matrix LED", "Bang & Olufsen", "AI Active Suspension", "Virtual Cockpit"],
    images: ["audi-a8-2024.jpg"],
    condition: "Used",
    location: "Dubai",
    featured: true,
    verified: true,
  },

  // Sports Cars
  {
    make: "Porsche",
    model: "911 Carrera",
    year: 2023,
    price: 525000,
    mileage: 5000,
    fuel: "Petrol",
    transmission: "Automatic",
    bodyType: "Coupe",
    color: "Guards Red",
    description: "Iconic sports car with legendary performance and precision handling",
    features: ["Sport Chrono", "PASM", "Sport Exhaust", "Track Mode"],
    images: ["porsche-911-2023.jpg"],
    condition: "Used",
    location: "Dubai",
    featured: true,
    verified: true,
  },
  {
    make: "BMW",
    model: "M4",
    year: 2024,
    price: 465000,
    mileage: 3000,
    fuel: "Petrol",
    transmission: "Automatic",
    bodyType: "Coupe",
    color: "BMW Individual Frozen Dark Grey",
    description: "High-performance coupe with twin-turbo engine and carbon fiber elements",
    features: ["M Drive Professional", "Carbon Roof", "M Seats", "Track Package"],
    images: ["bmw-m4-2024.jpg"],
    condition: "Used",
    location: "Dubai",
    featured: true,
    verified: true,
  },
  {
    make: "Mercedes",
    model: "AMG GT",
    year: 2023,
    price: 675000,
    mileage: 4000,
    fuel: "Petrol",
    transmission: "Automatic",
    bodyType: "Coupe",
    color: "AMG Green Hell Magno",
    description: "Track-bred sports car with handcrafted AMG engine",
    features: ["Race Mode", "AMG Ride Control", "Performance Exhaust", "Carbon Package"],
    images: ["mercedes-amg-gt-2023.jpg"],
    condition: "Used",
    location: "Abu Dhabi",
    featured: true,
    verified: true,
  },

  // SUVs - Premium
  {
    make: "Range Rover",
    model: "Velar",
    year: 2024,
    price: 385000,
    mileage: 7000,
    fuel: "Hybrid",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "Byron Blue",
    description: "Sophisticated luxury SUV with minimalist design and advanced technology",
    features: ["Air Suspension", "Meridian Audio", "Terrain Response", "Touch Pro Duo"],
    images: ["range-rover-velar-2024.jpg"],
    condition: "Used",
    location: "Dubai",
    featured: true,
    verified: true,
  },
  {
    make: "BMW",
    model: "X5",
    year: 2023,
    price: 325000,
    mileage: 15000,
    fuel: "Diesel",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "Carbon Black",
    description: "Versatile luxury SUV perfect for family adventures",
    features: ["xDrive", "Panoramic Roof", "Harman Kardon", "Driving Assistant Pro"],
    images: ["bmw-x5-2023.jpg"],
    condition: "Used",
    location: "Sharjah",
    featured: false,
    verified: true,
  },
  {
    make: "Mercedes",
    model: "GLC",
    year: 2024,
    price: 295000,
    mileage: 9000,
    fuel: "Hybrid",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "Polar White",
    description: "Compact luxury SUV with excellent fuel efficiency",
    features: ["4MATIC", "MBUX", "Burmester Audio", "Active Brake Assist"],
    images: ["mercedes-glc-2024.jpg"],
    condition: "Used",
    location: "Dubai",
    featured: false,
    verified: true,
  },
  {
    make: "Audi",
    model: "Q7",
    year: 2023,
    price: 365000,
    mileage: 11000,
    fuel: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "Mythos Black",
    description: "Three-row luxury SUV with quattro all-wheel drive",
    features: ["Virtual Cockpit Plus", "B&O Audio", "Air Suspension", "Matrix LED"],
    images: ["audi-q7-2023.jpg"],
    condition: "Used",
    location: "Abu Dhabi",
    featured: false,
    verified: true,
  },

  // Mid-Range Sedans
  {
    make: "Toyota",
    model: "Camry",
    year: 2024,
    price: 125000,
    mileage: 15000,
    fuel: "Hybrid",
    transmission: "Automatic",
    bodyType: "Sedan",
    color: "Silver Metallic",
    description: "Reliable and efficient sedan with Toyota Safety Sense 2.0",
    features: ["Adaptive Cruise Control", "Lane Keep Assist", "Wireless CarPlay", "JBL Audio"],
    images: ["toyota-camry-2024.jpg"],
    condition: "Used",
    location: "Dubai",
    featured: true,
    verified: true,
  },
  {
    make: "Honda",
    model: "Accord",
    year: 2023,
    price: 115000,
    mileage: 20000,
    fuel: "Hybrid",
    transmission: "Automatic",
    bodyType: "Sedan",
    color: "Still Night Pearl",
    description: "Spacious and fuel-efficient sedan with Honda Sensing",
    features: ["Honda Sensing", "Wireless Charging", "Bose Audio", "Head-Up Display"],
    images: ["honda-accord-2023.jpg"],
    condition: "Used",
    location: "Sharjah",
    featured: true,
    verified: true,
  },
  {
    make: "Nissan",
    model: "Altima",
    year: 2024,
    price: 95000,
    mileage: 8000,
    fuel: "Petrol",
    transmission: "Automatic",
    bodyType: "Sedan",
    color: "Scarlet Ember",
    description: "Modern sedan with ProPILOT Assist and Zero Gravity seats",
    features: ["ProPILOT Assist", "Zero Gravity Seats", "Remote Engine Start", "Bose Audio"],
    images: ["nissan-altima-2024.jpg"],
    condition: "Used",
    location: "Dubai",
    featured: false,
    verified: true,
  },
  {
    make: "Hyundai",
    model: "Sonata",
    year: 2023,
    price: 85000,
    mileage: 22000,
    fuel: "Petrol",
    transmission: "Automatic",
    bodyType: "Sedan",
    color: "Hampton Gray",
    description: "Stylish sedan with comprehensive warranty and advanced safety features",
    features: ["SmartSense", "Digital Key", "Wireless CarPlay", "Premium Audio"],
    images: ["hyundai-sonata-2023.jpg"],
    condition: "Used",
    location: "Ajman",
    featured: false,
    verified: true,
  },

  // Electric Vehicles
  {
    make: "Tesla",
    model: "Model S",
    year: 2024,
    price: 485000,
    mileage: 2000,
    fuel: "Electric",
    transmission: "Automatic",
    bodyType: "Sedan",
    color: "Pearl White Multi-Coat",
    description: "High-performance electric sedan with Autopilot and over-the-air updates",
    features: ["Autopilot", "Ludicrous Mode", "17-inch Display", "Premium Audio"],
    images: ["tesla-model-s-2024.jpg"],
    condition: "Used",
    location: "Dubai",
    featured: true,
    verified: true,
  },
  {
    make: "BMW",
    model: "iX",
    year: 2023,
    price: 425000,
    mileage: 6000,
    fuel: "Electric",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "Mineral Grey",
    description: "Luxury electric SUV with cutting-edge technology and sustainable materials",
    features: ["iDrive 8", "Panoramic Roof", "Harman Kardon", "Wireless Charging"],
    images: ["bmw-ix-2023.jpg"],
    condition: "Used",
    location: "Abu Dhabi",
    featured: true,
    verified: true,
  },
  {
    make: "Audi",
    model: "e-tron GT",
    year: 2023,
    price: 565000,
    mileage: 3500,
    fuel: "Electric",
    transmission: "Automatic",
    bodyType: "Sedan",
    color: "Daytona Grey",
    description: "Electric grand tourer with quattro all-wheel drive and rapid charging",
    features: ["quattro", "Air Suspension", "Bang & Olufsen", "Virtual Cockpit"],
    images: ["audi-e-tron-gt-2023.jpg"],
    condition: "Used",
    location: "Dubai",
    featured: true,
    verified: true,
  },

  // Compact SUVs
  {
    make: "Toyota",
    model: "RAV4",
    year: 2024,
    price: 145000,
    mileage: 12000,
    fuel: "Hybrid",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "Magnetic Gray",
    description: "Versatile compact SUV with excellent fuel economy and AWD capability",
    features: ["AWD", "Toyota Safety Sense", "Wireless CarPlay", "JBL Audio"],
    images: ["toyota-rav4-2024.jpg"],
    condition: "Used",
    location: "Dubai",
    featured: true,
    verified: true,
  },
  {
    make: "Honda",
    model: "CR-V",
    year: 2023,
    price: 135000,
    mileage: 18000,
    fuel: "Hybrid",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "Metallic Green",
    description: "Spacious and efficient compact SUV with Honda Sensing suite",
    features: ["Honda Sensing", "Real Time AWD", "Hands-Free Liftgate", "Bose Audio"],
    images: ["honda-cr-v-2023.jpg"],
    condition: "Used",
    location: "Sharjah",
    featured: false,
    verified: true,
  },
  {
    make: "Mazda",
    model: "CX-5",
    year: 2024,
    price: 125000,
    mileage: 14000,
    fuel: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "Soul Red Crystal",
    description: "Stylish compact SUV with SKYACTIV technology and premium interior",
    features: ["i-ACTIVSENSE", "SKYACTIV-G", "Bose Audio", "Apple CarPlay"],
    images: ["mazda-cx5-2024.jpg"],
    condition: "Used",
    location: "Dubai",
    featured: false,
    verified: true,
  },

  // Trucks & Utility
  {
    make: "Ford",
    model: "F-150",
    year: 2023,
    price: 185000,
    mileage: 25000,
    fuel: "Petrol",
    transmission: "Automatic",
    bodyType: "Truck",
    color: "Oxford White",
    description: "America's best-selling pickup truck with impressive towing capacity",
    features: ["4WD", "Trailer Tow Package", "SYNC 4", "Co-Pilot360"],
    images: ["ford-f150-2023.jpg"],
    condition: "Used",
    location: "Ras Al Khaimah",
    featured: false,
    verified: true,
  },
  {
    make: "Chevrolet",
    model: "Silverado",
    year: 2024,
    price: 175000,
    mileage: 18000,
    fuel: "Petrol",
    transmission: "Automatic",
    bodyType: "Truck",
    color: "Summit White",
    description: "Heavy-duty pickup truck with advanced trailering technology",
    features: ["4WD", "Trailering Package", "Infotainment 3", "Safety Assist"],
    images: ["chevrolet-silverado-2024.jpg"],
    condition: "Used",
    location: "Fujairah",
    featured: false,
    verified: true,
  },

  // Budget-Friendly Options
  {
    make: "Kia",
    model: "Forte",
    year: 2023,
    price: 65000,
    mileage: 28000,
    fuel: "Petrol",
    transmission: "Automatic",
    bodyType: "Sedan",
    color: "Clear White",
    description: "Affordable sedan with comprehensive warranty and modern features",
    features: ["UVO Connect", "Drive Wise", "Wireless CarPlay", "Premium Audio"],
    images: ["kia-forte-2023.jpg"],
    condition: "Used",
    location: "Ajman",
    featured: false,
    verified: true,
  },
  {
    make: "Hyundai",
    model: "Elantra",
    year: 2024,
    price: 72000,
    mileage: 16000,
    fuel: "Petrol",
    transmission: "Automatic",
    bodyType: "Sedan",
    color: "Intense Blue",
    description: "Compact sedan with bold styling and advanced technology",
    features: ["SmartSense", "BlueLink", "Wireless Charging", "Bose Audio"],
    images: ["hyundai-elantra-2024.jpg"],
    condition: "Used",
    location: "Sharjah",
    featured: false,
    verified: true,
  },
  {
    make: "Volkswagen",
    model: "Jetta",
    year: 2023,
    price: 78000,
    mileage: 21000,
    fuel: "Petrol",
    transmission: "Automatic",
    bodyType: "Sedan",
    color: "Tornado Red",
    description: "German-engineered sedan with turbocharged engine and digital cockpit",
    features: ["Digital Cockpit", "Car-Net", "Beats Audio", "IQ.DRIVE"],
    images: ["volkswagen-jetta-2023.jpg"],
    condition: "Used",
    location: "Dubai",
    featured: false,
    verified: true,
  },
  {
    make: "Mitsubishi",
    model: "Lancer",
    year: 2023,
    price: 68000,
    mileage: 24000,
    fuel: "Petrol",
    transmission: "Automatic",
    bodyType: "Sedan",
    color: "Rally Red",
    description: "Reliable compact sedan with excellent value and fuel efficiency",
    features: ["RISE Safety", "Smartphone Link", "Premium Audio", "Cruise Control"],
    images: ["mitsubishi-lancer-2023.jpg"],
    condition: "Used",
    location: "Umm Al Quwain",
    featured: false,
    verified: true,
  }
];

// Enhanced seed function to replace the existing one in server.js
app.post("/api/admin/seed-enhanced", async (req, res) => {
  try {
    // Clear existing cars
    await Car.deleteMany({});
    
    // Insert enhanced sample cars
    await Car.insertMany(enhancedSampleCars);
    
    res.json({
      message: "Database seeded successfully with enhanced car collection",
      count: enhancedSampleCars.length,
      categories: {
        luxury: enhancedSampleCars.filter(car => car.price > 300000).length,
        midRange: enhancedSampleCars.filter(car => car.price >= 100000 && car.price <= 300000).length,
        budget: enhancedSampleCars.filter(car => car.price < 100000).length,
        electric: enhancedSampleCars.filter(car => car.fuel === "Electric").length,
        hybrid: enhancedSampleCars.filter(car => car.fuel === "Hybrid").length,
        featured: enhancedSampleCars.filter(car => car.featured).length
      }
    });
  } catch (error) {
    console.error("Enhanced seed error:", error);
    res.status(500).json({ error: "Internal server error" });
  }
});

// Alternative: Direct MongoDB insertion script (run separately)
// Save this as seedCars.js and run with: node seedCars.js

/*
const mongoose = require('mongoose');
require('dotenv').config();

// Use the same Car model schema as in server.js
const carSchema = new mongoose.Schema({
  // ... same schema as in server.js
});

const Car = mongoose.model('Car', carSchema);

async function seedDatabase() {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/autosphere');
    
    // Clear existing data
    await Car.deleteMany({});
    
    // Insert new data
    await Car.insertMany(enhancedSampleCars);
    
    console.log(`Successfully seeded ${enhancedSampleCars.length} cars`);
    process.exit(0);
  } catch (error) {
    console.error('Seeding failed:', error);
    process.exit(1);
  }
}

seedDatabase();
*/

// Image filename mappings for your frontend
const carImageMap = {
  "Mercedes S-Class": "mercedes-s-class-2024.jpg",
  "BMW 7 Series": "bmw-7-series-2023.jpg",
  "Audi A8": "audi-a8-2024.jpg",
  "Porsche 911 Carrera": "porsche-911-2023.jpg",
  "BMW M4": "bmw-m4-2024.jpg",
  "Mercedes AMG GT": "mercedes-amg-gt-2023.jpg",
  "Range Rover Velar": "range-rover-velar-2024.jpg",
  "BMW X5": "bmw-x5-2023.jpg",
  "Mercedes GLC": "mercedes-glc-2024.jpg",
  "Audi Q7": "audi-q7-2023.jpg",
  "Toyota Camry": "toyota-camry-2024.jpg",
  "Honda Accord": "honda-accord-2023.jpg",
  "Nissan Altima": "nissan-altima-2024.jpg",
  "Hyundai Sonata": "hyundai-sonata-2023.jpg",
  "Tesla Model S": "tesla-model-s-2024.jpg",
  "BMW iX": "bmw-ix-2023.jpg",
  "Audi e-tron GT": "audi-e-tron-gt-2023.jpg",
  "Toyota RAV4": "toyota-rav4-2024.jpg",
  "Honda CR-V": "honda-cr-v-2023.jpg",
  "Mazda CX-5": "mazda-cx5-2024.jpg",
  "Ford F-150": "ford-f150-2023.jpg",
  "Chevrolet Silverado": "chevrolet-silverado-2024.jpg",
  "Kia Forte": "kia-forte-2023.jpg",
  "Hyundai Elantra": "hyundai-elantra-2024.jpg",
  "Volkswagen Jetta": "volkswagen-jetta-2023.jpg",
  "Mitsubishi Lancer": "mitsubishi-lancer-2023.jpg"
};

module.exports = { enhancedSampleCars, carImageMap };